name: Merge to integration

on:
  pull_request_review_comment:
    types: [created]


jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge to integration
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}
