name: Merge to integration
on: [pull_request_review_comment, pull_request]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge to integration
        uses: devmasx/merge-branch@main
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}
