name: Merge to integration
on:
  issue_comment:
    types: [created]

jobs:
  merge-branch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'deploy to integration/'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@master
        if: steps.check.outputs.triggered == 'true'
        with:
          ref: ${{ github.ref }}

      - name: Merge to integration
        if: steps.check.outputs.triggered == 'true'
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}

      - uses: khan/pull-request-comment-trigger@v1.1.0
        if: steps.check.outputs.triggered == 'true'
        id: check2
        with:
          trigger: 'deploy to integration/'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

