name: Merge to integration
on:
  issue_comment:
    types: [created]

jobs:
  merge-branch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure comment text should trigger a merge"
        uses: khan/pull-request-comment-trigger@v1.1.0
        with:
          trigger: 'deploy to integration/'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "get the base_ref of the branch in the pr" # this is part of the pull_request event but is not in the issue_comment :(
        uses: actions/github-script@v6
        id: pr-ref
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.rest.pulls.get(request)
              return result.data.head.ref
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: "Say Hello Mona it's Monday"
        run: echo "${{ steps.pr-ref.outputs.result }}"

      - name: "Merge branch into staging"
        uses: actions/github-script@v6
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "staging",
              head: ${{ steps.pr-ref.outputs.result }},
            }
            core.info(`Merging branch ${{ steps.pr-ref.outputs.result }} into "staging"`)
            try {
              const result = await github.rest.repos.merge(request);
              return result.data
            } catch (err) {
              console.log("TODO: leave a comment on the PR that we failed")
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: "Success! leave an emoji on the PR"
        uses: khan/pull-request-comment-trigger@v1.1.0
        with:
          trigger: 'deploy to integration/'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

